<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Carbon;

class MenuItemsSeeder extends Seeder
{
    public function run(): void
    {
        // Temporarily disable foreign key checks
        DB::statement('SET FOREIGN_KEY_CHECKS=0');
        
        // Clear the table
        DB::table('menu_items')->delete();
        
        $now = Carbon::now();

        // Get category IDs by name
        $categories = DB::table('menu_categories')->pluck('id', 'name');

        DB::table('menu_items')->insert([
            // Jerk Dishes
            [
                'category_id' => $categories['Jerk Dishes'],
                'name' => 'Jerk Chicken',
                'description' => null,
                'short_label' => null,
                'side_note' => null,
                'price' => 14.45,
                'image_path' => null,
                'is_featured' => false,
                'is_chef_special' => false,
                'is_available' => true,
                'is_visible' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => $categories['Jerk Dishes'],
                'name' => 'Jerk Prawns',
                'description' => null,
                'short_label' => null,
                'side_note' => null,
                'price' => 13.85,
                'image_path' => null,
                'is_featured' => false,
                'is_chef_special' => false,
                'is_available' => true,
                'is_visible' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => $categories['Jerk Dishes'],
                'name' => 'Jerk Chilli Prawn',
                'description' => null,
                'short_label' => null,
                'side_note' => null,
                'price' => 13.10,
                'image_path' => null,
                'is_featured' => false,
                'is_chef_special' => false,
                'is_available' => true,
                'is_visible' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => $categories['Jerk Dishes'],
                'name' => 'Honey Jerk Chicken',
                'description' => null,
                'short_label' => null,
                'side_note' => null,
                'price' => 14.05,
                'image_path' => null,
                'is_featured' => false,
                'is_chef_special' => false,
                'is_available' => true,
                'is_visible' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Meals
            [
                'category_id' => $categories['Meals'],
                'name' => 'Curry Goat Rice and Peas and Drink',
                'description' => null,
                'short_label' => null,
                'side_note' => null,
                'price' => 16.25,
                'image_path' => null,
                'is_featured' => false,
                'is_chef_special' => false,
                'is_available' => true,
                'is_visible' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => $categories['Meals'],
                'name' => 'Jamaican Fried Chicken Chips and Drink',
                'description' => null,
                'short_label' => null,
                'side_note' => null,
                'price' => 15.20,
                'image_path' => null,
                'is_featured' => false,
                'is_chef_special' => false,
                'is_available' => true,
                'is_visible' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => $categories['Meals'],
                'name' => 'Jerk Chicken Rice and Peas and Drink',
                'description' => null,
                'short_label' => null,
                'side_note' => null,
                'price' => 15.40,
                'image_path' => null,
                'is_featured' => false,
                'is_chef_special' => false,
                'is_available' => true,
                'is_visible' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => $categories['Meals'],
                'name' => 'Curry Chicken Plain Rice and Drink',
                'description' => null,
                'short_label' => null,
                'side_note' => null,
                'price' => 14.60,
                'image_path' => null,
                'is_featured' => false,
                'is_chef_special' => false,
                'is_available' => true,
                'is_visible' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Sides
            [
                'category_id' => $categories['Sides'],
                'name' => 'Festival Dumplings',
                'description' => null,
                'short_label' => null,
                'side_note' => null,
                'price' => 3.85,
                'image_path' => null,
                'is_featured' => false,
                'is_chef_special' => false,
                'is_available' => true,
                'is_visible' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => $categories['Sides'],
                'name' => 'Rice and Peas',
                'description' => null,
                'short_label' => null,
                'side_note' => null,
                'price' => 4.10,
                'image_path' => null,
                'is_featured' => false,
                'is_chef_special' => false,
                'is_available' => true,
                'is_visible' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => $categories['Sides'],
                'name' => 'Plain Rice',
                'description' => null,
                'short_label' => null,
                'side_note' => null,
                'price' => 3.65,
                'image_path' => null,
                'is_featured' => false,
                'is_chef_special' => false,
                'is_available' => true,
                'is_visible' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => $categories['Sides'],
                'name' => 'Coleslaw',
                'description' => null,
                'short_label' => null,
                'side_note' => null,
                'price' => 5.00,
                'image_path' => null,
                'is_featured' => false,
                'is_chef_special' => false,
                'is_available' => true,
                'is_visible' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => $categories['Sides'],
                'name' => 'Mac and Cheese',
                'description' => null,
                'short_label' => null,
                'side_note' => null,
                'price' => 5.00,
                'image_path' => null,
                'is_featured' => false,
                'is_chef_special' => false,
                'is_available' => true,
                'is_visible' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => $categories['Sides'],
                'name' => 'Hard Food (Yam Banana Dumpling)',
                'description' => null,
                'short_label' => null,
                'side_note' => null,
                'price' => 3.65,
                'image_path' => null,
                'is_featured' => false,
                'is_chef_special' => false,
                'is_available' => true,
                'is_visible' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Wraps
            [
                'category_id' => $categories['Wraps'],
                'name' => 'Jerk Chicken Wrap',
                'description' => null,
                'short_label' => null,
                'side_note' => null,
                'price' => 12.60,
                'image_path' => null,
                'is_featured' => false,
                'is_chef_special' => false,
                'is_available' => true,
                'is_visible' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => $categories['Wraps'],
                'name' => 'Full Belly Wrap',
                'description' => 'Jerk chicken, mac and cheese and salad in a lovely tortilla wrap with jerk sauce',
                'short_label' => null,
                'side_note' => null,
                'price' => 0.00,
                'image_path' => null,
                'is_featured' => false,
                'is_chef_special' => false,
                'is_available' => false,
                'is_visible' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Platters
            [
                'category_id' => $categories['Platters'],
                'name' => 'Seafood Platter',
                'description' => 'Lobster, prawns, mussels, squid, crab',
                'short_label' => null,
                'side_note' => null,
                'price' => 22.55,
                'image_path' => null,
                'is_featured' => false,
                'is_chef_special' => false,
                'is_available' => true,
                'is_visible' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => $categories['Platters'],
                'name' => 'Smokehouse Family Platter',
                'description' => 'Prawns, curry goat, jerk chicken or fry chicken x2 rice,x1 coleslaw x4 festivals',
                'short_label' => null,
                'side_note' => null,
                'price' => 26.75,
                'image_path' => null,
                'is_featured' => false,
                'is_chef_special' => false,
                'is_available' => true,
                'is_visible' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Mains with Rice and Peas
            [
                'category_id' => $categories['Mains with Rice and Peas'],
                'name' => 'Steam Fish',
                'description' => null,
                'short_label' => null,
                'side_note' => null,
                'price' => 19.40,
                'image_path' => null,
                'is_featured' => false,
                'is_chef_special' => false,
                'is_available' => true,
                'is_visible' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => $categories['Mains with Rice and Peas'],
                'name' => 'Ackee and Salt Fish',
                'description' => null,
                'short_label' => null,
                'side_note' => null,
                'price' => 14.60,
                'image_path' => null,
                'is_featured' => false,
                'is_chef_special' => false,
                'is_available' => true,
                'is_visible' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => $categories['Mains with Rice and Peas'],
                'name' => 'Escovitch Fish',
                'description' => null,
                'short_label' => null,
                'side_note' => null,
                'price' => 16.80,
                'image_path' => null,
                'is_featured' => false,
                'is_chef_special' => false,
                'is_available' => true,
                'is_visible' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => $categories['Mains with Rice and Peas'],
                'name' => 'Oxtail',
                'description' => null,
                'short_label' => null,
                'side_note' => null,
                'price' => 15.65,
                'image_path' => null,
                'is_featured' => false,
                'is_chef_special' => false,
                'is_available' => true,
                'is_visible' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => $categories['Mains with Rice and Peas'],
                'name' => 'Jamaican Fried Chicken',
                'description' => null,
                'short_label' => null,
                'side_note' => null,
                'price' => 13.10,
                'image_path' => null,
                'is_featured' => false,
                'is_chef_special' => false,
                'is_available' => true,
                'is_visible' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => $categories['Mains with Rice and Peas'],
                'name' => 'Stew Chicken',
                'description' => null,
                'short_label' => null,
                'side_note' => null,
                'price' => 13.10,
                'image_path' => null,
                'is_featured' => false,
                'is_chef_special' => false,
                'is_available' => true,
                'is_visible' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => $categories['Mains with Rice and Peas'],
                'name' => 'Coconut Prawns',
                'description' => null,
                'short_label' => null,
                'side_note' => null,
                'price' => 13.10,
                'image_path' => null,
                'is_featured' => false,
                'is_chef_special' => false,
                'is_available' => true,
                'is_visible' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => $categories['Mains with Rice and Peas'],
                'name' => 'Seafood Boil',
                'description' => 'Lobster prawns, corn, crab, egg, potato',
                'short_label' => null,
                'side_note' => null,
                'price' => 21.95,
                'image_path' => null,
                'is_featured' => false,
                'is_chef_special' => false,
                'is_available' => true,
                'is_visible' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => $categories['Mains with Rice and Peas'],
                'name' => 'BBQ Chicken',
                'description' => null,
                'short_label' => null,
                'side_note' => null,
                'price' => 15.20,
                'image_path' => null,
                'is_featured' => false,
                'is_chef_special' => false,
                'is_available' => true,
                'is_visible' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Lobster
            [
                'category_id' => $categories['Lobster'],
                'name' => 'Deep Fried Lobster',
                'description' => null,
                'short_label' => null,
                'side_note' => 'Serves with two sides',
                'price' => 18.80,
                'image_path' => null,
                'is_featured' => false,
                'is_chef_special' => false,
                'is_available' => true,
                'is_visible' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => $categories['Lobster'],
                'name' => 'Garlic Butter Lobster',
                'description' => null,
                'short_label' => null,
                'side_note' => 'Serves with two sides',
                'price' => 18.80,
                'image_path' => null,
                'is_featured' => false,
                'is_chef_special' => false,
                'is_available' => true,
                'is_visible' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => $categories['Lobster'],
                'name' => 'Jerk Pit Lobster Tail',
                'description' => null,
                'short_label' => null,
                'side_note' => 'Serves with two sides',
                'price' => 20.15,
                'image_path' => null,
                'is_featured' => false,
                'is_chef_special' => false,
                'is_available' => true,
                'is_visible' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Dessert
            [
                'category_id' => $categories['Dessert'],
                'name' => 'Vanilla Ice Cream',
                'description' => null,
                'short_label' => null,
                'side_note' => null,
                'price' => 5.25,
                'image_path' => null,
                'is_featured' => false,
                'is_chef_special' => false,
                'is_available' => true,
                'is_visible' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'category_id' => $categories['Dessert'],
                'name' => 'Rum Cake',
                'description' => null,
                'short_label' => null,
                'side_note' => null,
                'price' => 5.75,
                'image_path' => null,
                'is_featured' => false,
                'is_chef_special' => false,
                'is_available' => true,
                'is_visible' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ]);
    }
}
